from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ChangeLog(object):
    def setupUi(self, ChangeLog):
        ChangeLog.setObjectName("ChangeLog")
        ChangeLog.resize(623, 510)
        self.buttonBox = QtWidgets.QDialogButtonBox(ChangeLog)
        self.buttonBox.setGeometry(QtCore.QRect(270, 470, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(ChangeLog)
        self.label.setGeometry(QtCore.QRect(20, 30, 62, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ChangeLog)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 62, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ChangeLog)
        self.label_3.setGeometry(QtCore.QRect(20, 250, 62, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ChangeLog)
        self.label_4.setGeometry(QtCore.QRect(400, 30, 71, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(ChangeLog)
        self.pushButton.setGeometry(QtCore.QRect(20, 190, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(ChangeLog)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 270, 581, 191))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lineEdit = QtWidgets.QLineEdit(ChangeLog)
        self.lineEdit.setGeometry(QtCore.QRect(20, 50, 261, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(ChangeLog)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 130, 261, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(ChangeLog)
        self.calendarWidget.setGeometry(QtCore.QRect(293, 50, 301, 211))
        self.calendarWidget.setObjectName("calendarWidget")

        self.retranslateUi(ChangeLog)
        self.buttonBox.accepted.connect(ChangeLog.accept)
        self.buttonBox.rejected.connect(ChangeLog.reject)
        QtCore.QMetaObject.connectSlotsByName(ChangeLog)

    def retranslateUi(self, ChangeLog):
        _translate = QtCore.QCoreApplication.translate
        ChangeLog.setWindowTitle(_translate("ChangeLog", "Dialog"))
        self.label.setText(_translate("ChangeLog", "Name"))
        self.label_2.setText(_translate("ChangeLog", "Email"))
        self.label_3.setText(_translate("ChangeLog", "Message"))
        self.label_4.setText(_translate("ChangeLog", "Pick a date"))
        self.pushButton.setText(_translate("ChangeLog", "Import from CVS"))

